### ISSUE TITLE
build failed on extracting zlib1g.

### ISSUE THREAD

**Issue by deckikwok** [docker-linux/kali#2]
noob here. on building sh file face the following error:

sudo sh build-kali.sh
Reading package lists... Done
Building dependency tree  
Reading state information... Done
debootstrap is already the newest version (1.0.80+kali1).
0 upgraded, 0 newly installed, 0 to remove and 1292 not upgraded.

....
...
I: Extracting passwd...
I: Extracting perl-base...
I: Extracting procps...
I: Extracting sed...
I: Extracting sensible-utils...
I: Extracting startpar...
I: Extracting systemd...
I: Extracting systemd-sysv...
I: Extracting sysv-rc...
I: Extracting sysvinit-utils...
I: Extracting tar...
I: Extracting tzdata...
I: Extracting udev...
I: Extracting util-linux...
I: Extracting zlib1g...
Build failed!

Not sure what is the error. Please advise.

**Comment by Liberxue** [comment]
root@19c880bc4650:/# bash sh.sh
Reading package lists... Done
Building dependency tree
Reading state information... Done
debootstrap is already the newest version (1.0.90kali1).
The following package was automatically installed and is no longer required:
  libicu57
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6140    0  6140    0     0   1856      0 --:--:--  0:00:03 --:--:--  1856
I: Retrieving InRelease
I: Retrieving Release
E: Failed getting release file http://http.kali.org/kali/dists/kali-current/Release
Build failed!

**Comment by spencerdcarlson** [comment]
`kale-current` has been changed to `kali-rolling` 
Run this command to update the `build-kali.sh` script

`$ sed 's/kali-current/kali-rolling/g' < build-kali.sh > build-kali.sh.new && rm build-kali.sh && mv build-kali.sh.new build-kali.sh`
